version: '3.4'

networks:
  dev:
    driver: bridge

volumes:
  app_data:


services:
  app_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app_db
    container_name: app_api
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=server=${DB_HOST};port=${DB_PORT};database=${DB_NAME};user=${DB_USER};password=${DB_PASSWORD}
      - ASPNETCORE_URLS=http://+:80
      - SECRET_KEY_JWT=${SECRET_KEY_JWT}
    networks:
      - dev

  app_db:
    image: mysql:5.7
    container_name: app_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always
    volumes:
      - app_data:/var/lib/mysql
    networks:
      - dev
